remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
# theme: jekyll-theme-minimal
# theme: jekyll-theme-cayman@v0.2.0
title: Awesome LLM Software Testing
description: A collection of papers and resources about the utilization of large language models (LLMs) in software testing.
show_downloads: false